### ISSUE TITLE
Gradle files are missing

### ISSUE THREAD

**Issue by phcoder** [msx80/Omicron#5]
There is no gradlew and build.gradle which makes impossible to build player

**Comment by msx80** [comment]
Hi there, i'm transitioning to maven for the player. There wasn't any special need for gradle and i prefer vanilla maven when possible.  
You can build the player with `mvn clean package` to build, the runnable jar will be in omicron-assembly\target

**Comment by phcoder** [comment]
Can you update README to reflect this?

**Comment by msx80** [comment]
sure, just did it
